import type { Metadata } from "next";
import "./globals.css";
import '@fontsource-variable/onest';
import NavBar from "@/components/NavBar";
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale }
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();

  return (
    <html lang={locale}>
       <head>
        <link rel="icon" href="/favicon_io/favicon.ico"/>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body>
        <NextIntlClientProvider messages={messages}>
          {children}
          <NavBar />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
